### PR TITLE
Update tex with some settings

### PR DESCRIPTION
**Pull request by Spacebody**
Add usepacakges: graphicx
Add newcommands to add source to images
Add optional setting to usetheme
Add optional setting to split

### CODE REVIEW

**Comment by tengattack** [comment]
It make sense. However, we are long away from using this slides tex, do you want to be a collaborator of this project? @ProfFan could you make a review for this PR?

**Comment by Spacebody** [comment]
That’s okay.
tengattack <notifications@github.com>于2017年12月28日 周四19:40写道：

**Comment by tengattack** [comment]
OK, I sent a invite to you.

**Comment by ProfFan** [comment]
I think the quality needs to be improved. I reverted these changes.

**Comment by ProfFan** [comment]
@Spacebody it is more appropriate to consolidate all the changes you want to make and `squash` them into one big commit. The coding style needs cleanup as well.

**Comment by ProfFan** [comment]
@Spacebody Also be sure to include a demo file. Please test all changes with PDFLaTeX and XeLaTeX. If we have a lot of logos, it is better if we put them into a separate folder and have vector versions of them.

**Comment by Spacebody** [comment]
@ProfFan Sorry for many culpable places.  I have been used the modified files and they are no problem. I originally pull this request since I just wanted to make it less rigid a template for users with more flexible and useful settings. I do not put any new demo since previous one, your slide, I think, is enough to show the probable effect of this template. Not all the setting will be used for a slide but if you must want to provide all the demo of the settings, that is time consuming.  As I suggest, comment is fine. I did not squash the commit into a big commit it since the changes are for different files but it will be okay if commit with "Version updated and more features added", whatever, that is not a big problem.

**Pull request merged**
